//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoutique
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenderorsRecord
    {
        public int Order_Id { get; set; }
        public string Article_No { get; set; }
        public Nullable<int> No_Of_Suits { get; set; }
        public Nullable<int> Colors { get; set; }
        public Nullable<int> Price_For_Each { get; set; }
        public Nullable<System.DateTime> Added_On { get; set; }
        public string Image_Path { get; set; }
        public Nullable<int> Paid_Amount { get; set; }
        public Nullable<int> Remaining_Amount { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public string Vendor_Id { get; set; }
    }
}
